# Generated by Django 2.0.6 on 2018-10-26 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_taginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleInfo', verbose_name='所属文章')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.TagInfo', verbose_name='所属标签')),
            ],
            options={
                'verbose_name': '文章标签信息',
                'verbose_name_plural': '文章标签信息',
            },
        ),
        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('article', 'tag')},
        ),
    ]
